name: deploy
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Make 3D contribution graph
        uses: yoshi389111/github-profile-3d-contrib@208d8215bd117497a02c94f559f94474ba23819c # v0.9.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SETTING_JSON: settings.json
          USERNAME: ${{ github.repository_owner }}
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@df5cc2bfa78282ded844b354faee141f06b41865 # v4.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          build_dir: profile-3d-contrib
          commit_message: "chore: update artifacts"
          target_branch: profile-3d-contrib
